# ----------------------------------------------------------------------------------------------------------------------
# DATABASE
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ingresos_reingresos_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: password123
    driver-class-name: com.mysql.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
# ----------------------------------------------------------------------------------------------------------------------
# JWT
security:
  auth:
    jwt:
      secret: some-secret
      expiration: 3600
    password:
      salt-rounds: 10 # Default is 10
# ----------------------------------------------------------------------------------------------------------------------