# ----------------------------------------------------------------------------------------------------------------------
# DATABASE
spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: ${MYSQL_DRIVER_NAME}
  sql:
    init:
      mode: ${MYSQL_INIT_MODE}
  jpa:
    show-sql: ${MYSQL_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_SQL_FORMAT_SQL}
        dialect: ${HIBERNATE_DIALECT}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_TYPE}
    generate-ddl: ${HIBERNATE_GENERATE_DDL}
# ----------------------------------------------------------------------------------------------------------------------
# JWT
security:
  auth:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION_SECS}
# ----------------------------------------------------------------------------------------------------------------------