# ----------------------------------------------------------------------------------------------------------------------
# Application
spring:
  application:
    name: ingresos-reingresos-backend
  profiles:
    active: local
# ----------------------------------------------------------------------------------------------------------------------
# Server
server:
  port: 8080
# ----------------------------------------------------------------------------------------------------------------------